server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true

spring:
  application:
    name: eurekaserver
  profiles:
    active: dev
    
---
spring:
  profiles: dev
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: server1
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: server3
server:
  port: 8763
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/